
services:
  web:
    container_name: application-backend
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code

  postgresql:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: application-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

